### ISSUE TITLE
[OBS] make OBS standard

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/gophertelekomcloud#80]
Currently, OBS uses its own implementation of client and isolated from other parts of the library, re-implementing some already implemented features.

OBS should be rewritten in the same manner, as other modules are written now.

**Comment by Aloento** [comment]
Let me do it.

**Comment by Aloento** [comment]
Due to the specificity of OBS: 
it uses XML instead of JSON, and the URL of the requested OBS request changes according to the bucket:
`protocol://[bucket.]domain[:port][/object][?param]`
And the header has to carry the user signature, 
so it is better not to use the common Client.

The refactoring and updates will be done in #431.

**Comment by outcatcher** [comment]
> And the header has to carry the user signature,

It does

>it uses XML instead of JSON

Changes should be done to the lower layer, client don't need to know about content type, you can specify it explicitly.

>and the URL of the requested OBS request changes according to the bucket

Same for CCE nodes and addons
